// app/components/payroll/PayrollRecordTable.vue
<script setup lang="ts">
import type { PayrollSheetRecordRow } from '~/types'

interface Props {
  records: PayrollSheetRecordRow[]
  isMutating?: boolean
}

const props = withDefaults(defineProps<Props>(), {
  isMutating: false,
})

const emit = defineEmits<{
  updateNetPay: [recordId: number, netPay: number]
  updateExportWeight: [recordId: number, exportWeight: number | null]
  removePersonnel: [personnelId: number]
}>()

const editingNetPay = ref<number | null>(null)
const editingExportWeight = ref<number | null>(null)
const netPayInput = ref<string>('')
const exportWeightInput = ref<string>('')

const formatCurrency = (value: number | null): string => {
  if (value === null || value === undefined) return '0.00'
  return value.toFixed(2)
}

const startEditNetPay = (record: PayrollSheetRecordRow) => {
  if (props.isMutating) return
  editingNetPay.value = record.recordId
  netPayInput.value = record.netPay !== null && record.netPay !== undefined ? String(record.netPay) : ''
}

const handleNetPayBlur = (record: PayrollSheetRecordRow) => {
  const value = parseFloat(netPayInput.value)
  if (!isNaN(value) && value !== record.netPay) {
    emit('updateNetPay', record.recordId, value)
  }
  editingNetPay.value = null
}

const handleNetPayKeydown = (e: KeyboardEvent, record: PayrollSheetRecordRow) => {
  if (e.key === 'Enter') {
    handleNetPayBlur(record)
  } else if (e.key === 'Escape') {
    editingNetPay.value = null
  }
}

const startEditExportWeight = (record: PayrollSheetRecordRow) => {
  if (props.isMutating) return
  editingExportWeight.value = record.recordId
  exportWeightInput.value = record.exportWeight !== null && record.exportWeight !== undefined
    ? String(record.exportWeight)
    : ''
}

const handleExportWeightBlur = (record: PayrollSheetRecordRow) => {
  const trimmed = exportWeightInput.value.trim()
  if (trimmed === '') {
    if (record.exportWeight !== null) {
      emit('updateExportWeight', record.recordId, null)
    }
  } else {
    const value = parseFloat(trimmed)
    if (!isNaN(value) && value !== record.exportWeight) {
      emit('updateExportWeight', record.recordId, value)
    }
  }
  editingExportWeight.value = null
}

const handleExportWeightKeydown = (e: KeyboardEvent, record: PayrollSheetRecordRow) => {
  if (e.key === 'Enter') {
    handleExportWeightBlur(record)
  } else if (e.key === 'Escape') {
    editingExportWeight.value = null
  }
}
</script>

<template>
  <div class="bg-white rounded-lg shadow overflow-hidden">
    <div class="overflow-x-auto">
      <table class="min-w-full divide-y divide-gray-200">
        <thead class="bg-gray-50">
          <tr>
            <th class="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider w-16">
              序号
            </th>
            <th class="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
              姓名
            </th>
            <th class="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
              身份证号
            </th>
            <th class="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
              银行卡号
            </th>
            <th class="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
              开户行
            </th>
            <th class="px-4 py-3 text-right text-xs font-medium text-gray-500 uppercase tracking-wider w-36">
              实发工资
            </th>
            <th class="px-4 py-3 text-right text-xs font-medium text-gray-500 uppercase tracking-wider w-32">
              外运重量
            </th>
            <th class="px-4 py-3 text-center text-xs font-medium text-gray-500 uppercase tracking-wider w-24">
              操作
            </th>
          </tr>
        </thead>
        <tbody class="bg-white divide-y divide-gray-200">
          <tr v-if="records.length === 0">
            <td colspan="8" class="px-4 py-12 text-center text-gray-500">
              暂无人员，请点击"添加人员"按钮添加
            </td>
          </tr>
          <tr
            v-for="(record, index) in records"
            :key="record.recordId"
            class="hover:bg-gray-50 transition-colors"
          >
            <td class="px-4 py-3 text-sm text-gray-500">
              {{ index + 1 }}
            </td>
            <td class="px-4 py-3 text-sm font-medium text-gray-900">
              {{ record.name }}
            </td>
            <td class="px-4 py-3 text-sm text-gray-500 font-mono text-xs">
              {{ record.idCardNumber || '-' }}
            </td>
            <td class="px-4 py-3 text-sm text-gray-500 font-mono text-xs">
              {{ record.payrollCardNumber || '-' }}
            </td>
            <td class="px-4 py-3 text-sm text-gray-500">
              {{ record.bankName || '-' }}
            </td>
            <td class="px-4 py-3 text-sm text-right">
              <div v-if="editingNetPay === record.recordId">
                <input
                  ref="netPayInputRef"
                  v-model="netPayInput"
                  type="number"
                  step="0.01"
                  min="0"
                  class="w-full px-2 py-1 text-right border border-blue-500 rounded focus:outline-none focus:ring-1 focus:ring-blue-500 text-sm"
                  @blur="handleNetPayBlur(record)"
                  @keydown="handleNetPayKeydown($event, record)"
                  :disabled="isMutating"
                  autofocus
                />
              </div>
              <div
                v-else
                class="cursor-pointer text-green-600 font-medium hover:text-green-700 hover:bg-green-50 px-2 py-1 rounded -mx-2 transition-colors"
                @click="startEditNetPay(record)"
              >
                ¥{{ formatCurrency(record.netPay) }}
              </div>
            </td>
            <td class="px-4 py-3 text-sm text-right">
              <div v-if="editingExportWeight === record.recordId">
                <input
                  v-model="exportWeightInput"
                  type="number"
                  step="0.01"
                  min="0"
                  placeholder="可空"
                  class="w-full px-2 py-1 text-right border border-blue-500 rounded focus:outline-none focus:ring-1 focus:ring-blue-500 text-sm"
                  @blur="handleExportWeightBlur(record)"
                  @keydown="handleExportWeightKeydown($event, record)"
                  :disabled="isMutating"
                  autofocus
                />
              </div>
              <div
                v-else
                class="cursor-pointer text-gray-600 hover:text-gray-900 hover:bg-gray-100 px-2 py-1 rounded -mx-2 transition-colors"
                @click="startEditExportWeight(record)"
              >
                <template v-if="record.exportWeight !== null && record.exportWeight !== undefined">
                  {{ record.exportWeight }}
                </template>
                <template v-else>
                  <span class="text-gray-400">-</span>
                </template>
              </div>
            </td>
            <td class="px-4 py-3 text-sm text-center">
              <button
                @click="emit('removePersonnel', record.personnelId)"
                class="text-red-600 hover:text-red-800 font-medium transition-colors"
                :disabled="isMutating"
              >
                移除
              </button>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</template>

// src/components/payroll/payroll-record-table.tsx
"use client";

import { useState } from "react";
import {
  Table,
  TableHeader,
  TableRow,
  TableHead,
  TableBody,
  TableCell,
} from "@/components/ui/table";
import { Checkbox } from "@/components/ui/checkbox";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import type { PayrollSheetRecordRow } from "@/lib/types";
import { payrollApi } from "@/lib/api";
import { toast } from "sonner";
import { Trash2, Edit3, Check, X } from "lucide-react";

type Props = {
  records: PayrollSheetRecordRow[];
  sheetId: number;
  selectedRecordIds: Set<number>;
  onToggleSelect: (id: number) => void;
  onToggleSelectAll: () => void;
  onRefresh: () => void;
};

export function PayrollRecordTable({
  records,
  sheetId,
  selectedRecordIds,
  onToggleSelect,
  onToggleSelectAll,
  onRefresh,
}: Props) {
  const [editingId, setEditingId] = useState<number | null>(null);
  const [editingField, setEditingField] = useState<"netPay" | "exportWeight" | null>(
    null
  );
  const [editValue, setEditValue] = useState<string>("");
  const [saving, setSaving] = useState(false);

  const totalNetPay = records.reduce((sum, r) => sum + r.netPay, 0);

  const startEdit = (
    record: PayrollSheetRecordRow,
    field: "netPay" | "exportWeight"
  ) => {
    setEditingId(record.recordId);
    setEditingField(field);
    const value = field === "netPay" ? record.netPay : record.exportWeight;
    setEditValue(value != null ? String(value) : "");
  };

  const cancelEdit = () => {
    setEditingId(null);
    setEditingField(null);
    setEditValue("");
  };

  const saveEdit = async () => {
    if (editingId == null || !editingField) return;
    setSaving(true);
    try {
      if (editingField === "netPay") {
        const value = parseFloat(editValue);
        if (isNaN(value)) {
          toast.error("请输入有效的金额");
          return;
        }
        await payrollApi.updateNetPay(editingId, value);
      } else if (editingField === "exportWeight") {
        const value = editValue.trim() === "" ? null : parseInt(editValue);
        if (editValue.trim() !== "" && isNaN(value as number)) {
          toast.error("请输入有效的序号");
          return;
        }
        await payrollApi.updateExportWeight(editingId, value as number | null);
      }
      toast.success("保存成功");
      onRefresh();
      cancelEdit();
    } catch (error: any) {
      toast.error(error.message || "保存失败");
    } finally {
      setSaving(false);
    }
  };

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === "Enter") {
      saveEdit();
    } else if (e.key === "Escape") {
      cancelEdit();
    }
  };

  const handleRemoveSelected = async () => {
    if (selectedRecordIds.size === 0) return;
    try {
      await payrollApi.removePersonnel(sheetId, Array.from(selectedRecordIds));
      toast.success(`已移除 ${selectedRecordIds.size} 人`);
      onRefresh();
    } catch (error: any) {
      toast.error(error.message || "移除失败");
    }
  };

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between">
        <div className="text-sm text-muted-foreground">
          共 {records.length} 条记录，实发合计：
          <span className="font-semibold text-foreground ml-1">
            ¥{totalNetPay.toLocaleString("zh-CN", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}
          </span>
        </div>
        {selectedRecordIds.size > 0 && (
          <Button
            variant="destructive"
            size="sm"
            onClick={handleRemoveSelected}
          >
            <Trash2 className="size-4 mr-2" />
            移除选中 ({selectedRecordIds.size})
          </Button>
        )}
      </div>
      <div className="rounded-md border overflow-x-auto">
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead className="w-12">
                <Checkbox
                  checked={
                    records.length > 0 &&
                    selectedRecordIds.size === records.length
                  }
                  onCheckedChange={onToggleSelectAll}
                  aria-label="全选"
                />
              </TableHead>
              <TableHead className="w-16">序号</TableHead>
              <TableHead>姓名</TableHead>
              <TableHead>身份证号</TableHead>
              <TableHead>银行卡号</TableHead>
              <TableHead>账户银行</TableHead>
              <TableHead className="w-28 text-right">实发金额</TableHead>
              <TableHead className="w-24 text-center">导出序号</TableHead>
              <TableHead>联系电话</TableHead>
              <TableHead className="w-20">操作</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {records.length === 0 ? (
              <TableRow>
                <TableCell
                  colSpan={10}
                  className="text-center py-8 text-muted-foreground"
                >
                  暂无记录，请先添加工员
                </TableCell>
              </TableRow>
            ) : (
              records.map((record, index) => (
                <TableRow key={record.recordId}>
                  <TableCell>
                    <Checkbox
                      checked={selectedRecordIds.has(record.recordId)}
                      onCheckedChange={() => onToggleSelect(record.recordId)}
                      aria-label="选择"
                    />
                  </TableCell>
                  <TableCell className="text-muted-foreground text-sm">
                    {index + 1}
                  </TableCell>
                  <TableCell className="font-medium">{record.name}</TableCell>
                  <TableCell className="font-mono text-xs">
                    {record.idCardNumber || "-"}
                  </TableCell>
                  <TableCell className="font-mono text-xs">
                    {record.payrollCardNumber || "-"}
                  </TableCell>
                  <TableCell className="text-sm">
                    {record.bankName || "-"}
                  </TableCell>
                  <TableCell className="text-right">
                    {editingId === record.recordId && editingField === "netPay" ? (
                      <div className="flex items-center gap-1 justify-end">
                        <Input
                          type="number"
                          step="0.01"
                          value={editValue}
                          onChange={(e) => setEditValue(e.target.value)}
                          onKeyDown={handleKeyDown}
                          disabled={saving}
                          className="w-24 text-right h-8"
                          autoFocus
                        />
                        <Button
                          size="icon"
                          variant="ghost"
                          className="size-8"
                          onClick={saveEdit}
                          disabled={saving}
                        >
                          <Check className="size-4 text-green-600" />
                        </Button>
                        <Button
                          size="icon"
                          variant="ghost"
                          className="size-8"
                          onClick={cancelEdit}
                          disabled={saving}
                        >
                          <X className="size-4 text-destructive" />
                        </Button>
                      </div>
                    ) : (
                      <div
                        className="cursor-pointer hover:text-primary font-mono"
                        onClick={() => startEdit(record, "netPay")}
                      >
                        ¥{record.netPay.toLocaleString("zh-CN", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}
                        <Edit3 className="size-3 inline ml-1 opacity-0 group-hover:opacity-100" />
                      </div>
                    )}
                  </TableCell>
                  <TableCell className="text-center">
                    {editingId === record.recordId && editingField === "exportWeight" ? (
                      <div className="flex items-center gap-1 justify-center">
                        <Input
                          type="number"
                          value={editValue}
                          onChange={(e) => setEditValue(e.target.value)}
                          onKeyDown={handleKeyDown}
                          disabled={saving}
                          className="w-16 text-center h-8"
                          placeholder="-"
                          autoFocus
                        />
                        <Button
                          size="icon"
                          variant="ghost"
                          className="size-8"
                          onClick={saveEdit}
                          disabled={saving}
                        >
                          <Check className="size-4 text-green-600" />
                        </Button>
                        <Button
                          size="icon"
                          variant="ghost"
                          className="size-8"
                          onClick={cancelEdit}
                          disabled={saving}
                        >
                          <X className="size-4 text-destructive" />
                        </Button>
                      </div>
                    ) : (
                      <div
                        className="cursor-pointer"
                        onClick={() => startEdit(record, "exportWeight")}
                      >
                        {record.exportWeight != null ? (
                          <Badge variant="secondary">{record.exportWeight}</Badge>
                        ) : (
                          <span className="text-muted-foreground">-</span>
                        )}
                      </div>
                    )}
                  </TableCell>
                  <TableCell className="font-mono text-xs">
                    {record.phoneNumber || "-"}
                  </TableCell>
                  <TableCell>
                    <Button
                      variant="ghost"
                      size="icon"
                      onClick={async () => {
                        try {
                          await payrollApi.removePersonnel(sheetId, [
                            record.personnelId,
                          ]);
                          toast.success("已移除");
                          onRefresh();
                        } catch (e: any) {
                          toast.error(e.message || "移除失败");
                        }
                      }}
                    >
                      <Trash2 className="size-4 text-destructive" />
                    </Button>
                  </TableCell>
                </TableRow>
              ))
            )}
          </TableBody>
        </Table>
      </div>
    </div>
  );
}
